### PR TITLE
support for mixed base OS

### LINKED ISSUE #110: support mixed base OS for the cluster
If you have a RHEL and deb based OS images in same cluster, current role won't work

add support for mixed base OS

### PR DESCRIPTION
**Pull request by tarzanek**
fixes #110

### CODE REVIEW

**Comment by tarzanek** [comment]
tests done with old config that just had scylla_repos (et al)
and new configs that just had 
scylla_deb_repos
and
scylla_rpm_repos

field cloud test pending

**Review by vladzcloudius — APPROVED** [review]
LGTM
Make sure to test it for both cases.

**Comment by tarzanek** [comment]
field cloud test in progress: http://localhost:8081/job/Testing/job/Create_cluster_tarzanek_repo/28/console

**Comment by tarzanek** [comment]
test field cloud for new options:
http://localhost:8081/job/Testing/job/Create_cluster_tarzanek_repo/32/console

**Pull request merged**
