### PR TITLE
add cpuset

### LINKED ISSUE #19: settings for perftune for sq_split don't get applied
https://github.com/scylladb/scylla-ansible-roles/blob/master/ansible-scylla-node/tasks/common.yml#L176
only prints the config, it won't set it

what should be done is (for 2019):

```
scylla_cpuset_setup --cpuset `/usr/lib/scylla/perftune.py --tune net --get-cpu-mask --nic eth0 --mode sq_split | /usr/lib/scylla/hex2list.py`
```

### LINKED ISSUE #28: cpuset is not run
https://github.com/scylladb/scylla-ansible-roles/blob/master/ansible-scylla-node/tasks/common.yml#L166

just figures out the cpuset mask
but never sets it anywhere

so obviously for smaller machines sq_split won't be applied

### PR DESCRIPTION
**Pull request by tarzanek**
fixes #28
fixes #19

### CODE REVIEW

**Comment by dyasny** [comment]
LGTM

**Comment by tarzanek** [comment]
can the "run perftune" block that happens afer cpuset be removed @dyasny ?

**Comment by dyasny** [comment]
if all it does it print to stdout, then yes. We need an actual tuning here, not just a check

**Comment by tarzanek** [comment]
ok, since I tested this I will commit and then look at perftune run - fwiw first scylla start runs perftune based on cpuset anyways

**Pull request merged**
