### PR TITLE
Support ubuntu 20.04 (focal)

### PR DESCRIPTION
**Pull request by stevedrip**
Scylla server successfully starts on ubuntu focal after adding both this and the following PR:
https://github.com/scylladb/scylla-ansible-roles/pull/35

Not tested on production yet, nor have I attempted to install scylla manager.

### CODE REVIEW

**Comment by dyasny** [comment]
Since this only changes meta, does it mean you've tested against Focal, and it worked?

**Comment by stevedrip** [comment]
That's correct, though our team has only stood up a cluster and hasn't done any performance testing, tuning, or production deployments.

**Comment by tarzanek** [comment]
per https://github.com/scylladb/scylla/issues/6343
support for 20.04 will be in 4.3.1

can we restrict this support only for certain versions? @dyasny ?

**Comment by dyasny** [comment]
We can add a check at the start of the Debian.yml for scylla version and OS version. Something like:

```yaml
- fail:
    msg: "This Scylla version is incompatible with Ubuntu 20.x"
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "20" and scylla_edition == "oss" and scylla_actual_version >= "4.3.1"
```

All that is left is a quick `set_fact` for `scylla_actual_version` before this task, getting the installed version from apt or dpkg

**Comment by tarzanek** [comment]
merging, since we support 20.04 now

**Pull request merged**
