### PR TITLE
molecule: upgrade ansible to 6.7.0

### PR DESCRIPTION
**Pull request by tarzanek**

### CODE REVIEW

**Comment by tarzanek** [comment]
@sharonovd still works on this, so while this fixes dependencies, it lacks fix for containers

**Comment by tarzanek** [comment]
@sharonovd can you review or merge if you're ok with this?

**Comment by sharonovd** [comment]
Note to self - we need to switch CI to self-hosted runner, because public runners don't allow this style of dind for some reason now.

**Review by sharonovd — APPROVED** [review]

**Comment by tarzanek** [comment]
let's move the containers not being able to start to a different issue then

**Pull request merged**
